---
#cloud_controller_uri:
#  host: api.vcap.me
#  port: 80
service:
  name: atmos
  version: "1.4"
  description: 'Atmos object storage'
  plans: ['free']
  tags: ['atmos', 'atmos-1.4', 'object storage']
host: localhost
token: "0xdeadbeef"
mbus: nats://localhost:4222
log_level: DEBUG
pid: /var/vcap/sys/run/atmos_service.pid

# atmos configuration
# Not configured by default as it would require revealing
# credentials to a non-local resource.
#aux:
#  atmos_host: "172.0.0.1"
#  atmos_port: "443"
#  atmos_tenant: "tenant"
#  atmos_tenantadmin: "admin"
#  atmos_tenantpasswd: "password"
