# Gateway URI should include IP and port
gateway_uri: 10.135.81.79:57363
instance_id: redis-507aeff6-1a40-41d6-8f82-0f4971e92d31
backup_path: /mnt/appcloud/backups/redis/d7/70/e3/d770e3ac-e1de-4f5b-813f-3dd76b33c3b7/1304670778
# The mode can be restore or recover
mode: recover
