networks: (( merge ))

meta:
  release:
    name: cf-services-contrib

jobs:
  - name: rabbit_gateway
    release: (( meta.release.name ))
    template:
      - rabbit_gateway
    instances: 1
    resource_pool: gateway_z1
    networks:
      - name: services1
        static_ips: (( merge ))

  - name: rabbit_node
    release: (( meta.release.name ))
    template: rabbit_node_ng
    instances: 1
    resource_pool: node_z1
    persistent_disk: 10000
    networks:
      - name: services1
        static_ips: (( merge ))
    properties:
      plan: default


